spring:
  datasource:
    url: jdbc:${DATABASE_URL}?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
