spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quack?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    path: /docs
